In [ ]:
# 1
x1,y1 = 0,2
x2,y2 = 3,5

x3 = 2

y3 = y1 + ((x3-x1)*(y2-y1))/(x2-x1)
print(y3)

In [ ]:
# 2
# x' = xcostheta - ysintheta
# y' = xsintheta + ycostheta

import numpy as np
import math

x,y = 3,2
theta = math.pi/6

cos30 = math.cos(theta)
sin30 = math.sin(theta)

x_rotated = x*cos30 - y*sin30
y_rotated =  x*sin30 + y*cos30

x_final = x_rotated + 5
y_final = x_rotated + 7

print(f'({x_final},{y_final})')

In [ ]:
# 4
import numpy as np
k = int(input("Any constant: "))
H = np.array((5,7,1))
H = np.matrix(H.reshape(3,1))
print(H)

Any constant: 2
[[10]
 [14]
 [ 0]]


In [ ]:
# 5
def plane_intersect(a, b):
    """
    a, b   4-tuples/lists
           Ax + By +Cz + D = 0
           A,B,C,D in order  

    output: 2 points on line of intersection, np.arrays, shape (3,)
    """
    a_vec, b_vec = np.array(a[:3]), np.array(b[:3])
    aXb_vec = np.cross(a_vec, b_vec)

    A = np.array([a_vec, b_vec, aXb_vec])
    d = np.array([-a[3], -b[3], 0.]).reshape(3,1)

# could add np.linalg.det(A) == 0 test to prevent linalg.solve throwing error

    p_inter = np.linalg.solve(A, d).T
    return p_inter[0], (p_inter + aXb_vec)[0]

a, b = (2, 1, -1, -3), (1, -1, 1, -3)
plane_intersect(a, b)

# a> line
# 2x+y-z = 3 
# x-y+z = 3
# z = 2x+y-3    z = 3-x+y
# 2x+y-3 = 3-x+y
# 3x = 6 
# => x = 2
# 2-y+z = 3 
# z = 1+y
# (2,y,1+y)
# Putting z = 0
# (2,-1,0)

(array([ 2. , -0.5,  0.5]), array([ 2. , -3.5, -2.5]))

In [ ]:
# 6
import numpy as np
import math
A = [(5,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1)]
print(A)

theta = math.pi/6

cos30 = math.cos(theta)
sin30 = math.sin(theta)
B = [(cos30,sin30,0,0),(-sin30,cos30,0,0),(0,0,1,0),(0,0,0,1)]
H1 = np.matmul(A,B)
print(B)
print(H1)
C = np.matmul([(1,2,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1)],[(1,0,0,0),(3,1,0,0),(0,0,1,0),(0,0,0,1)])
H2 = np.matmul(H1,C)
print(C)
print(H2)
D = [(1,0,0,0,2),(0,1,0,0,1),(0,0,1,0,2),(0,0,0,1,1)]
H = np.matmul(H2,D)
print(D)
print(H)

[(5, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)]
[(0.8660254037844387, 0.49999999999999994, 0, 0), (-0.49999999999999994, 0.8660254037844387, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)]
[[ 4.33012702  2.5         0.          0.        ]
 [-0.5         0.8660254   0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[7 2 0 0]
 [3 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[37.81088913 11.16025404  0.          0.        ]
 [-0.90192379 -0.1339746   0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[(1, 0, 0, 0, 2), (0, 1, 0, 0, 1), (0, 0, 1, 0, 2), (0, 0, 0, 1, 1)]
[[37.81088913 11.16025404  0.          0.         86.7820323 ]
 [-0.90192379 -0.1339746   0.          0.         -1.93782217]
 [ 0.          0.          1.          0.          2.        ]
 [ 0.          0.          0.          1.          1.        ]]


In [ ]:
# 8
import numpy as np
import math

A = [5,9,4,1]

theta1 = math.pi/6
theta2 = math.pi/2
theta3 = math.pi

cos30 = math.cos(theta1)
sin30 = math.sin(theta1)
cos90 = math.cos(theta2)
sin90 = math.sin(theta2)
cos180 = math.cos(theta3)
sin180 = math.sin(theta3)

Z_rot = [(cos30,sin30,0,0),(-sin30,cos30,0,0),(0,0,1,0),(0,0,0,1)]
Y_rot = [(cos90,0,-sin90,0),(0,1,0,0),(sin90,0,cos90,0),(0,0,0,1)]
X_rot = [(1,0,0,0),(0,cos180,sin180,0),(0,-sin180,cos180,0),(0,0,0,1)]
T = [(1,0,0,4),(0,1,0,-3),(0,0,1,7),(0,0,0,1)]
H1 = np.matmul(Z_rot,A)
H2 = np.matmul(Y_rot,H1)
H3 = np.matmul(X_rot,H2)
H = np.matmul(T,H3)

print(H)

[ 4.44089210e-16 -8.29422863e+00 -1.83012702e+00  1.00000000e+00]


In [ ]:

# 9

import numpy as np
import cv2 as cv

points_2d = [(880, 214), (43, 203), (270, 197), (886, 347), (745, 302), (943, 128), (476, 590), 
    (419, 214), (317, 335), (783, 521), (235, 427), (665, 429), (665, 362), (427, 333),
    (412, 415), (746, 351), (434, 415), (525, 234), (716, 308), (602, 187)]
points_3d = [(312.747, 309.140, 30.086), (305.796, 311.649, 30.356), (307.694, 312.358, 30.418), (310.149, 307.186, 29.298),
    (311.937, 310.105, 29.216), (311.202, 307.572, 30.682), (307.106, 306.876, 28.660), (309.317, 312.490, 30.230),
    (307.435, 310.151, 29.318), (308.253, 306.300, 28.881), (306.650, 309.301, 28.905), (308.069, 306.831, 29.189),
    (309.671, 308.834, 29.029), (308.255, 309.955, 29.267), (307.546, 308.613, 28.963), (311.036, 309.206, 28.913),
    (307.518, 308.175, 29.069), (309.950, 311.262, 29.990), (312.160, 310.772, 29.080), (311.988, 312.709, 30.514)]

# for i in I_pt:
#   for j in W_pt:
#     i = np.matrix(i)
#     j = np.matrix(j)
#     i_transpose = i.getI()
#     p = np.matmul(i_transpose,j)
#     i += 1
#     j +=1
#     # print(p)
#     d = cv.decomposeProjectionMatrix(p)
#     print (d)


# # # print(W)
# # print(W_transpose)

# # P = np.matmul() 

A = np.zeros((2*len(points_3d), 12))

print(A.shape)
for i in range(0, A.shape[0], 2):
    A[i, 0] = points_3d[int(i/2)][0]
    A[i, 1] = points_3d[int(i/2)][1]
    A[i, 2] = points_3d[int(i/2)][2]
    A[i, 3] = 1
    A[i, 8] = -1 * points_2d[int(i/2)][0] * points_3d[int(i/2)][0]
    A[i, 9] = -1 * points_2d[int(i/2)][0] * points_3d[int(i/2)][1]
    A[i, 10] = -1 * points_2d[int(i/2)][0] * points_3d[int(i/2)][2]
    A[i, 11] = -1 * points_2d[int(i/2)][0] 
    A[i+1, 4] = points_3d[int(i/2)][0]
    A[i+1, 5] = points_3d[int(i/2)][1]
    A[i+1, 6] = points_3d[int(i/2)][2]
    A[i+1, 7] = 1
    A[i+1, 8] = -1 * points_2d[int(i/2)][1] * points_3d[int(i/2)][0]
    A[i+1, 9] = -1 * points_2d[int(i/2)][1] * points_3d[int(i/2)][1]
    A[i+1, 10] = -1 * points_2d[int(i/2)][1] * points_3d[int(i/2)][2]
    A[i+1, 11] = -1 * points_2d[int(i/2)][1]

U, S, Vh = np.linalg.svd(A)

V = Vh.T

M = Vh[-1,:]

M = np.reshape(M, (3,4))

print(M)

jk = [i for i in points_3d[16]]
jk.append(1)
print(jk)

lk = np.matmul(M, np.array(jk))

print(lk/lk[-1])


(40, 12)
[[ 3.09551512e-03  1.50099363e-04 -4.55089945e-04 -9.78699360e-01]
 [ 3.08995055e-04  6.37417029e-04 -2.76003823e-03 -2.05250740e-01]
 [ 1.68238445e-06  2.74302661e-06 -6.69612696e-07 -1.32883746e-03]]
[307.518, 308.175, 29.069, 1]
[434.5856895  415.14063795   1.        ]


In [ ]:
# 10
import numpy as np

M = [(512,-800,0,800),(512,0,-800,1600),(1,0,0,0)]

W = [4,0,0,1]

I = np.matmul(M,W)
print(I)

[2848 3648    4]
